name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pre make
      run: mkdir bin
    - name: make
      run: make noip
    - name: Archive artifacts (NOIP Checker)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: NOIP Checker
        path: bin/noip
